### PR TITLE
Added process: warp_projection

### LINKED ISSUE #22: Warp projection - missing process?
I think we currently don't have a process that warps a projection. SInce this is a fairly common operation to do, I would propose to add it to the process list.

### PR DESCRIPTION
**Pull request by lforesta**
I'm not sure which of the existing categories is suitable, I tentatively added a category 'spatial'.
Closes #22

### CODE REVIEW

**Comment by m-mohr** [comment]
Great, thank you. I made some tweaks, but are also not sure about the categories yet. I put it into cubes and aggregate (to be combined with related operations such as resample and aggregate), but the category aggregate needs probably another name as warping is not really an aggregation method. Anybody ware of a better name?

**Comment by jdries** [comment]
looks good, about the description:
Warps the projection of a data cube to the target one
I would say:
Warps the data cube to the target projection

**Comment by lforesta** [comment]
> Warps the data cube to the target projection
I agree, much better than what I wrote.

**Comment by m-mohr** [comment]
Thanks, changed. Also improved the definition of the projection parameter.

**Comment by claxn** [comment]
Just a small comment from my side: In my opinion it would be convenient to specify a generic function `warp(raster_cube_source, raster_cube_target, resampling_method)`. As you have mentioned in the meeting today, the datacube object should have all spatial related properties (e.g. extent, projection, pixel spacing...). If the extent is different, you will get the same result as with `filter_bbox`, if you you want to resample the data (e.g. downsampling 10m->500m), then you change the spatial resolution of the target datacube and if you want to reproject, then you change the projection system of the target datacube. Then we would have only one function instead of multiple. Moreover, a function `clone_raster_cube` (i.e. copying all properties from a raster cube and creating an empty one) could be helpful in case a user only has to change one property instead of specifying all spatial attributes.

**Comment by mkadunc** [comment]
Do we need to better define what kind of datacube is returned? I guess it will have new geospatial axes, while all other axes will remain the same. Do we need to prescribe the coordinates (offset, spacing, extent) of the new axes, or do we allow backend to determine those in a proprietary way?

**Comment by m-mohr** [comment]
We better discuss this in a non-closed issue/PR such as #14.

**Pull request merged**
