### PR TITLE
#154 specify a chunk process

### PR DESCRIPTION
**Pull request by jdries**
Proposal for a 'chunk' process.

### CODE REVIEW

**Comment by edzer** [comment]
This is more like setting a parameter for a follow-up process, right? I don't think of "chunking" as a process (what would be the outcome of it?), but as a strategy.

**Comment by jdries** [comment]
Indeed, it would not have a visible effect. Although a backend that uses chunking internally could do things, but it would not be visible.
You could say that it makes 'chunks' a user visible property of our data cubes. Whereas until now it was probably there, but hidden. 
Maybe a 'positive' side effect is that this allows backends to specify their support for chunks through the processes API. If we simply add an optional chunking parameter to existing processes, backends would maybe not support it, but it would not be visible for the user...
(I'm myself not entirely decided on the best approach, just worked out one of the options to get some discussion going.)

**Comment by m-mohr** [comment]
Ah, now I understand #154 better. But now I'm wondering: Isn't that what we always said to abstract away from a user? How would a user know when to use this and what to set for the parameters? Especially this "physical measure" mapping seems unclear.

**Comment by edzer** [comment]
Yes, ideally, the back-end would be smart enough to sort this out, but I believe that in practice this is usually rather black magic (= trial and error).

**Comment by jdries** [comment]
The designer of the algorithm would know that he needs some padding for his data. Or for instance, for a machine learning model, he may have designed it to run on 128x128 patches spatially, and a 2 month period in time. (Those are the use cases that I'm running into.)

How to specify the chunks/padding indeed needs improvement. For a time dimension, people often use a 'physical' representation like x days, while for spatial it is more common to use pixels. (As people mostly design for a given sensor with a known resolution.)

**Comment by m-mohr** [comment]
Oh, I see. In the description it sounded more like a hardware than a algorithm issue though?!

Are there other similar options that we may need? I'm thinking whether this could be something to be set in load_collection or save_result. Having it as part of save_result would be pretty easy to integrate as we have format parameters etc. already integrated and so each back-end could handle that individually without any API/process change.

**Comment by jdries** [comment]
Problem is you might have multiple operations with different chunking/padding options. So having it in load_collection would work for the first operation, but not for the next. In save_result makes less sense, as it would give the impression that it's a property of the output format.
If adding to specific processes, the list would be fairly limited:
- apply
- apply-dimension
- reduce_dimension
Maybe we could define an object that specifies chunking options, and include that as a parameter. (That way we have only have to document the details in one place, but can reuse it in multiple processes.)

**Comment by m-mohr** [comment]
I see.

> * apply
> * apply-dimension
> * reduce_dimension
>   Maybe we could define an object that specifies chunking options, and include that as a parameter. (That way we have only have to document the details in one place, but can reuse it in multiple processes.)

They all have the context parameter, maybe back-ends can re-use that?

**Comment by jdries** [comment]
Or maybe just go for a new apply_chunk process, with a definition similar to apply dimension?
Instead of working on a single dimension, it would work on a multidimensional subcube.

**Comment by m-mohr** [comment]
From all mentioned alternatives, that seems to be the most reasonable approach.

**Comment by jdries** [comment]
Reworked it, I actually went for apply_neighbourhood, maybe better than 'chunk'? (Although I'm fine either way.)
reduce_neighbourhood could indeed also work, although it would be fairly similar to the apply variant.

In general I do have some (backend specific?) issues with what we allow in terms of changing dimensions:

- spatial dimensions can not really be messed with, I don't really support reducing them or changing dimension labels (that would be resampling)
- For the bands dimension: these have discrete labels, a neighbourhood operation would always work on all bands, are perhaps we could do something with bands indices.

**Comment by m-mohr** [comment]
@jdries, two organizational issues:
- This PR was made from master, not draft. I tried to change the branch to merge to from master to draft, but gives issues. Could you please either merge draft into the PR branch or redo the PR for draft?
- The build is failing. That also needs to be fixed, but I can also do that for you. Likely some spacing issues (no spaces before/after \n for example) and summary too long.


Regarding naming I'll check what would be most consistent with the other processes, but the parameter names are pretty long and relatively hard to type correctly, e.g. `neighbourhood_padding`. Would it be okay to shorten, e.g. to "size" and "padding"? Also, wouldn't "overlap" be more intuitive? I had to read the description to understand what's meant with padding, but likely would have directly known from "overlap". The schemas for size and padding are still to vague. It's not clear what the objects should be.

**Pull request closed without merging**
