### PR TITLE
Improve summary of order process

### PR DESCRIPTION
**Pull request by soxofaan**
spin-off from #409   :stuck_out_tongue:

### CODE REVIEW

**Comment by m-mohr** [comment]
A change here should probably be aligned with rearrange.

For me in this proposal it's not clear what the order is. This sounds a bit like whether it would return "ascending" or "descending" or "unsorted" and not the indices for the array in a sorted order ;-)

**Comment by soxofaan** [comment]
> A change here should probably be aligned with rearrange.

Because `rearrange` uses "permutation" in its summary?  I think that's fine.

> For me in this proposal it's not clear what the order is. This sounds a bit like whether it would return "ascending" or "descending" or "unsorted" 

Ok fair. An alternative, stealing from numpy argsort:

> Get indices that would sort the array


FYI: what I don't like about the current summary "Create a permutation":
- "create a" sound like the process just randomly generates some permutation, regardless of the original data
- "permutation": it's not always obvious if "permutation" refers to the set of indices to implement the rearrangement, or if it is about the result after rearranging 
so "create a permutation" roughly sounds like "randomly shuffle the array" to me

**Comment by m-mohr** [comment]
@soxofaan I made a couple of changes to the PR, especially to link between the processes. Can you check whether this works for you?

**Comment by soxofaan** [comment]
yes it's better now

apparently I can approve this PR, I guess because I started it myself

**Pull request merged**
