### PR TITLE
WIP: histogram reducer process with discrete buckets

### PR DESCRIPTION
**Pull request by bossie**

### CODE REVIEW

**Comment by m-mohr** [comment]
Thank you @bossie  for coming up with a process description for the histogram process.

For me there's room for improvement as it's not clear how exactly the process works and how the bins are computed.

For example, what would be the result for the following input?
* `[-0.6, -0,4, 0,3, 0.8]` (i.e. what happens if the step is not 1?)
* `[0, 55, 255]` (i.e. what happens with gaps?)

In addition, I think it's problematic to return a array of objects. We don't have processes to work on objects and therefore it will be impossible to get values out of the objects. We probably need a pure array approach or improvements to the processes. Issue #91 is highly related.

To solve both issues and make the process description clearer, I guess it could make sense to introduce a parameter that accepts an array of ranges. The indices of that array would be parallel to the returned array so that the process could simply return an array with the counts numbers.

**Comment by jdries** [comment]
We explicitly choose to leave room for how bins are computed, as there are indeed a number of cases. The only possible parameter that we could support is a maximum number of bins.

**Comment by m-mohr** [comment]
We should define it clearly. It's not useful for a user if it's not clear what is actually returned.

**Comment by jdries** [comment]
For cases with a limited number of unique values, like the examples you give above, I would expect having a bucket per unique value.
For cases with number of unique values exceeding a fixed or requested number of buckets, the backend needs to determine the min and max value, and then somehow spread buckets in this range. The most common approach is perhaps to spread them evenly?

**Comment by m-mohr** [comment]
@jdries Specifying a number of bins that are distributed evenly makes sense and would basically explain most of my questions. Question is whether the back-end should determin min/max or whether the user should be able to select it?

We should also add not so simply examples such as [-0.3667421020, 0.2468341124, 1.7006593618 -1.1597762280, 0.5253916115, 0.1204214514]...

**Comment by jdries** [comment]
One of my main use cases for histogram is figuring out the distribution of the data. So I use it in cases where I don't have a clue about min/max values. For this case these 'smart' histograms are very convenient. So the question is, what is the 80% use case? Smart binning with optimized but 'undefined' result, or user defined bins with perfectly reproducable results.

**Comment by m-mohr** [comment]
Not sure. We could also allow both...
If min and/or max are not specified, the back-end determines the missing min/max values.

So we would end up with something like `histogram(data, binCount, min = null, max = null)`? Or should binCount also be optional? How to describe the behavior of the process if binCount is undefined?

**Comment by m-mohr** [comment]
@bossie @jdries Will you be able to update this PR until Jan, 22?

**Comment by soxofaan** [comment]
> How to describe the behavior of the process if binCount is undefined?

numpy/matplotlib uses 10 bins by default. Which is a bit low IMHO however. We could pick a higher default (e.g. a power of two like 16 or 32).

**Comment by soxofaan** [comment]
Another thing not covered here yet is that a user also might want to get the bin bounds themselves. Especially if the user does not specify min/max explicitly.

**Comment by m-mohr** [comment]
@soxofaan I guess you could get the min/max values from the labels 🤔

**Comment by m-mohr** [comment]
Please be aware of the recent changes to the processes, which makes the parameters an array, removes parameter_order and moved the parameter name into the corresponding object.

**Comment by m-mohr** [comment]
Stale PR, please let me know whenever you have updated the process to 1.0.

**Pull request closed without merging**
