### PR TITLE
Remove binary reducers #258

### PR DESCRIPTION
**Pull request by m-mohr**
For discussion: Do we actually need the binary reducers and is someone planning to implement them? If not, we may want to clean-up and remove them as otherwise, we'd also need to provide them for e.g. reduce_spatial.

### CODE REVIEW

**Comment by jdries** [comment]
Actually we do support the binary variant in our backend, but do not seem to properly declare it:
https://github.com/Open-EO/openeo-python-driver/blob/master/openeo_driver/ProcessGraphDeserializer.py#L842

In fact, it could very well be that we don't properly support the non-binary variant...
Do we actually need them: not if the backend can auto-detect that an optimization is possible, in case the process (graph) is a commutative + associative reducer.

**Comment by m-mohr** [comment]
Good to know, I've only looked into the Hub and there was no back-end declaring support for it.

Back-ends can surely optimize if it doesn't influence the result. I think the main use case for the binary variants were UDFs.

This issue is pretty much to discuss whether we think those processes are still good to have or whether we could remove them (having in mind #226 and a potential new process `reduce_spatial_binary`). So all feedback will be appreciated.

**Comment by soxofaan** [comment]
> Actually we do support the binary variant in our backend, but do not seem to properly declare it:
https://github.com/Open-EO/openeo-python-driver/blob/master/openeo_driver/ProcessGraphDeserializer.py#L842

I don't think we (still) support it actually, as far as I understand, the related code path got lost during some 0.4-1.0  related refactors

**Comment by m-mohr** [comment]
Removing. Has not been implemented and the sole use-case is UDFs, which itself would likely not lead to good performance as binary UDFs are too fine-grained.

**Pull request merged**
